env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'prettier'
plugins:
  - 'prettier'
parserOptions:
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  prettier/prettier:
    - error
